config/routes.rb
Omrails::Application.routes.draw do 
  resources :sites

  resources :channels

  resources :comments

  resources :assets

  
    resources :pins  do
    member { post :vote }
    resources :comments
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

get 'about' => 'pages#about'
root :to => 'pins#index' 
post 'pins/:pin' => 'pins#copy', :as => :repin

end

app/models/channel.rb
class Channel < ActiveRecord::Base
  attr_accessible :description, :name
  
  validates :name, presence: true
  validates :description, presence: true
  validates :user_id, presence: true

  belongs_to :user
  has_many :pins, dependent: :destroy
  
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
 before_filter :authenticate_user!, except: [:index, :show]
  # GET /channels
  # GET /channels.json
  def index
    @channels = current_user.channels.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @channels }
    end
  end

  # GET /channels/1
  # GET /channels/1.json
  def show
    @channel = Channel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/new
  # GET /channels/new.json
  def new
    @channel = current_user.channels.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @channel }
    end
  end

  # GET /channels/1/edit
  def edit
    @channel = current_user.channels.find(params[:id])
  end

  # POST /channels
  # POST /channels.json
  def create
    @channel = current_user.channels.new(params[:channel])

    respond_to do |format|
      if @channel.save
        format.html { redirect_to @channel, notice: 'Channel was successfully created.' }
        format.json { render json: @channel, status: :created, location: @channel }
      else
        format.html { render action: "new" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /channels/1
  # PUT /channels/1.json
  def update
    @channel = current_user.channels.find(params[:id])

    respond_to do |format|
      if @channel.update_attributes(params[:channel])
        format.html { redirect_to @channel, notice: 'Channel was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @channel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /channels/1
  # DELETE /channels/1.json
  def destroy
    @channel = current_user.channel.find(params[:id])
    @channel.destroy

    respond_to do |format|
      format.html { redirect_to channels_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
end

app/views/channels/_channel.html.erb
<div class="box">

	<center> <h3> <%= channel.name %> </h3> </center> 
	<% @pin = channel.pins.last %>
	
	<a href="/channels/<%= channel.id %>"><img width="270" height="158" src="<%= @pin.thumb_url %>" frameborder="0" ></img></a> 

	
   <p>
    <%= channel.description %>
   </p>
   <p>
   <%= link_to 'Show', channel %> |
   <%= link_to 'Edit', edit_channel_path(channel) %>
   <%= link_to 'Destroy', channel, method: :delete, data: { confirm: 'Are you sure?' } %></p>
 

app/views/channels/_form.html.erb
<%= simple_form_for(@channel, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>

 
    <%= f.input :name %>
    <%= f.input :description, as: :text, input_html: {rows: "3"} %>
  

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/channels/edit.html.erb
<h1>Editing channel</h1>

<%= render 'form' %>

<%= link_to 'Show', @channel %> |
<%= link_to 'Back', channels_path %>

app/views/channels/index.html.erb
<h1>Listing channels</h1>
<% @channel = "0" %>


  
    <%= render @channels %>
  




<%= link_to 'New Channel', new_channel_path %>

app/views/channels/new.html.erb
<h1>New channel</h1>

<%= render 'form' %>

<%= link_to 'Back', channels_path %>

app/views/channels/show.html.erb
<div class="row">
	
		<div class="well">
				<p> <center> <h2> <%= @channel.name %> Channel</h2> </center> </p>
				<p>
				You are watching the <%= @channel.name %> channel for <%= @channel.description %>
				</p>
				<% if current_user == @channel.user %>
				<%= link_to 'Edit', edit_channel_path(@channel) %> |
				<% end %>
				<%= link_to 'View your Channels', channels_path %>
		</div>
		<div id="pins">
					  <%= render @channel.pins %> 
					</div> 
	
<div>
	
		