config/routes.rb
Omrails::Application.routes.draw do 
  resources :sites

  resources :channels

  resources :comments

  resources :assets

  
    resources :pins  do
    member { post :vote }
    resources :comments
  end

  devise_for :users, controllers: {omniauth_callbacks: "omniauth_callbacks"}

get 'about' => 'pages#about'
root :to => 'pins#index' 
post 'pins/:pin' => 'pins#copy', :as => :repin

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :yt_video_id, :channel_id, :site_id, :thumb_url


  validates :description, presence: true
  validates :user_id, presence: true
  validates :yt_video_id, presence: true
  validates :channel_id, presence: true
  validates :site_id, presence: true
  validates :thumb_url, presence: true
 
  belongs_to :user
  belongs_to :channel
  belongs_to :site
  has_reputation :votes, source: :user, aggregated_by: :sum
  has_many :comments, dependent: :destroy


def self.search(search)
  if search
    losearch = search.downcase
    find(:all, :conditions => ['lower(description) LIKE ?', "%#{losearch}%"], order: "created_at desc")
  else
    find_with_reputation(:votes, :all, order: "created_at desc")
    
  end
end
end

app/controllers/pins_controller.rb
 class PinsController < ApplicationController

  before_filter :authenticate_user!, except: [:index, :show]
  # GET /pins
  # GET /pins.json
  def index
    
    
    @pins = Pin.search(params[:search])
    
  
    
    @pins = @pins.paginate(:page => params[:page], :per_page => 20)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    
      @pin = current_user.pins.new()
      @pin.description = params[:description]
      @pin.thumb_url = params[:media]
        regExp = /http:\/\/(www\.)?vimeo.com\/(\d+)($|\/)/
       if params[:description] 
        if params[:yt_video_id]
          @pin.yt_video_id = params[:yt_video_id]
        else
          youtube_url = params[:url]
          match = youtube_url.match(regExp)
          if !match
            if youtube_url.match(/youtu\.be\/([^\?]*)/)
              @pin.yt_video_id = youtube_url.match(/youtu\.be\/([^\?]*)/)[1]
            else
              if youtube_url.match(/v=([^&]*)/)
                @pin.yt_video_id = youtube_url.match(/v=([^&]*)/)[1]
                @pin.site_id = "1"
              else
                
                @pin.yt_video_id = youtube_url.gsub('www','embed')
                @pin.site_id = "3"
              
              
              end
            end
          else
            @pin.yt_video_id = match[2]
            
            @pin.site_id = "2"

          end
        end
        @hidden = 'true'
      end
      

     
      
     
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.new(params[:pin])
    

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end

  def vote
    value = params[:type] == "up" ? 1 : -1
    @pin = Pin.find(params[:id])
    @pin.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back, notice: "Thank you for voting"
  end
  def copy
  
  pin = Pin.find(params[:pin])
  @channel = current_user.channels.last
  new_pin = current_user.pins.new(:description => pin.description, :yt_video_id => pin.yt_video_id, :site_id => pin.site_id, :channel_id => @channel.id, :thumb_url => pin.thumb_url)    
  respond_to do |format|
    
    if new_pin.save
      format.html { redirect_to edit_pin_path(new_pin)}
    else
      format.html { redirect_to root_url, notice: "Error saving pin." }
end
end
 # new_pin = current_user.pins.new(:description => pin.description, :yt_video_id => pin.yt_video_id)    
 # respond_to do |format|
 #   if new_pin.save
 #     format.html { redirect_to new_pin, notice: 'Pin was successfully created.' }
 #   else
 #     format.html { redirect_to root_url, notice: "Error saving pin." }
#end
#end

end
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert-error" %>
  <%= f.full_error :image_content_type, class: "alert-error" %>
  <table>
    <tr>
      <td>
  <%= f.input :channel_id, :label => "Channel", :collection => current_user.channels, :include_blank => false, :input_html => {:multiple => false} %>
      </td>
      <td>
       <%= link_to 'Add New Channel', new_channel_path %>
      </td>
    </tr>
  </table>
  <table>
    <tr>
      <td>
        <% if @hidden %>
          <%= f.input :yt_video_id, label: "Enter the video ID", :as => :hidden %>
          <%= f.input :thumb_url, :label => "Thumbnail URL", :as => :hidden %>
        <% else %>
        	<%= f.input :yt_video_id, label: "Enter the video ID" %>
          <%= f.input :thumb_url, :label => "Thumbnail URL" %>
        <% end %>
        <%= f.input :description, as: :text, input_html: { rows: "3" } %>
      </td>
      <td>
        <img src="<%= @pin.thumb_url %>"></img>

      </td>
    </tr>
  </table>
   <% @site = Site.all %>
    <% if @hidden %>
        <%= f.input :site_id, :label => "Site", :collection => @site, :include_blank => false, :input_html => {:multiple => false}, :as => :hidden %>
    <% else %>
         <%= f.input :site_id, :label => "Site", :collection => @site, :include_blank => false, :input_html => {:multiple => false} %>
    <% end %>
  

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">

<!--http://i3.ytimg.com/vi/<%= pin.yt_video_id %>/mqdefault.jpg 
http://www.youtube.com/embed/<%= pin.yt_video_id %> -->
<% if pin.site_id == 1 %>
	<a href="/pins/<%= pin.id %>"><img src="/assets/PlayButton.png" width="270" height="auto" border="0" style="background:URL(http://i3.ytimg.com/vi/<%= pin.yt_video_id %>/mqdefault.jpg) center center black;" frameborder="0" ></img>
		</span> 
	</a>
<% else %>
	<% if pin.site_id == 2 %>
		<a href="/pins/<%= pin.id %>"><img src="/assets/PlayButton.png" width="270" height="auto" border="0" style="background:URL(<%= pin.thumb_url %>) center center black;" frameborder="0" ></img>
	<% else %>
		<% if pin.site_id == 3 %>
			<a href="/pins/<%= pin.id %>"><img src="/assets/PlayButton.png" width="270" height="auto" border="0" style="background:URL(<%= pin.thumb_url %>) center center black;" frameborder="0" ></img>
		<% end %>
	<% end %>	
	</span> 
	</a>
<% end %> 

	<p class="description">
		<%= pin.description %>
	</p>
	<p>
		<strong>
			  Posted by <%= pin.user.name %>  
			  <%= image_tag(pin.user.image(:tiny), :alt => pin.user.name, :title => pin.user.name) %>
			  
		</strong>
	</p>
	<p>
		on <%= link_to(pin.channel.name, channel_path(pin.channel)) %> channel.
	<p>
		
	<% if current_user && !current_user.voted_for?(pin) %>
   <%= link_to(image_tag('up.png', :alt => "Like", :title => "Like"), vote_pin_path(pin, type: "up"), method: "post") %>
  
<% end %>
<%= pluralize pin.reputation_for(:votes).to_i, "like" %>
&nbsp <%= link_to(image_tag('comment.png', :alt => "Comment", :title => "Comments"), pin) %> 
		<% @pin = pin%>
		<%= @pin.comments.count %>
		<% if current_user == pin.user %>
		
&nbsp			<%= link_to(image_tag('edit.png', :alt => "Edit", :title => "Edit"), edit_pin_path(pin)) %>
&nbsp			<%= link_to(image_tag('delete.png' +"  ", :alt => "Delete", :title => "Delete"), pin, method: :delete, data: { confirm: 'Are you sure?' }) %>
&nbsp		<%= link_to(image_tag('show.png', :alt => "Show", :title => "Show"), pin) %>
		<% else %>
&nbsp		<%= link_to(image_tag('show.png', :alt => "Show", :title => "Show"), pin) %>
		<% end%>
		<% if user_signed_in? %>
  &nbsp <%= link_to(image_tag('repin.png', :alt => "Repin", :title => "Re-pin"), repin_path(pin), method: :post) %>
<% end %>
</p>
	
</div>      

app/views/pins/copy.html.erb
<h1>Re-pin</h1>

<%= render 'form' %>


<%= link_to 'Back', pins_path %>

app/views/pins/copy1.html.erb
<h1>Re-pin</h1>

<%= render 'form' %>


<%= link_to 'Back', pins_path %>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>



	
		
					<div id="pins">
					  <%= render @pins %>
					</div>
		
<%= will_paginate @pins %>

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/repin.html.erb
<h1>Re-pin</h1>

<%= render 'form' %>


<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span8 offset2">
		<div class="well">
			<% if @pin.site_id == 1 %>
			<iframe width="98%" height="415" src="http://www.youtube.com/embed/<%= @pin.yt_video_id %>?autoplay=1" frameborder="0" ></iframe>
			<% else %>
				<% if @pin.site_id == 2 %>
					<iframe src="http://player.vimeo.com/video/<%= @pin.yt_video_id %>" width="98%" height="415" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
				<% else %>
					<iframe src="<%= @pin.yt_video_id %>" width="98%" height="415" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
				<% end %>
			<% end %>

<p>

  <%= @pin.description %>
</p>
<p>
  
  <%= @pin.user.name %>
</p>
		<% if current_user == @pin.user %>
		<%= link_to 'Edit', edit_pin_path(@pin) %> |
		<% end %>
		<%= link_to 'Back', pins_path %>
		<H4>Comments</H4>
		<div id="comments">
			<%= render :partial => @pin.comments %>
		</div>
		<%= simple_form_for [@pin, Comment.new]	do |f| %>
		<p>
			<!--<%= f.label :body, "New Comment" %></br>
			<%= f.text_area :body %> -->
			<%= f.input :body, :label => "New Comment", as: :text, input_html: { rows: "3" } %>
		</p>
		<p><%= f.submit "Add Comment", class: "btn btn-primary" %></p>
<% end %>	

		</div>
	</div>
</div>